#!/bin/bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	BASE=$HOME/fsharp
elif [[ "$OSTYPE" == "darwin"* ]]; then
	BASE=$HOME/bin/fsharp
elif [[ "$OSTYPE" == "cygwin" ]]; then
	BASE=/usr/bin/fsharp
else
	BASE=$HOME/bin/fsharp
fi

FSLEX=$BASE/fslex.exe
mono $FSLEX --unicode $*
